#!/bin/sh
# $HOME/Downloads/birt-report-designer-all-in-one-4.12.0-20221128-linux.gtk.x86_64/eclipse/eclipse > ./eclipse.log 2> ./eclipse.err.log &
$HOME/eclipse/jee-2023-12//eclipse/eclipse > ./eclipse.log 2> ./eclipse.err.log &